#! /usr/bin/python

#
# Misison State Machine
#
# @brief This is the high level mission state machine. Dictates the mission 
#        timeline. Links the sub-state machines in the right order. 
#
# @author Riley Mark 
# @author Febuary 27, 2025
# 
#*******************************************************************************

import rospy
import smach
import smach_ros

from daedalus_core.pcs_move_states import *
from daedalus_core.pcs_states import *

class Mission_SM:
    def __init__(self):
        self.sm = smach.StateMachine(outcomes=["Mission_Success", "Mission_Fail"])

        self.mission_sm()
        
    def mission_sm(self):
        with self.sm:


            smach.StateMachine.add('inhibit_detect',
                                   Check_Inhibit(),
                                   transitions={'full_inhibit': 'Mission_Success',
                                                'partial_inhibit': 'ejector_sm',
                                                'no_inhibit': 'wait_0'})
            
            smach.StateMachine.add('ejector_sm',
                                   ejector_sm,
                                   transitions={'Complete': 'Mission_Success',
                                                'Fail': 'Mission_Fail'})

            smach.StateMachine.add('wait_0', 
                                   Wait_State(1),
                                   transitions={'Complete': 'wait_for_start_mission_signal'}) 
            
            smach.StateMachine.add('wait_for_start_mission_signal',
                                   Check_Signal(),
                                   transitions={'start_mission': 'wait_00',
                                                'not_yet': 'wait_for_start_mission_signal'})
            
            smach.StateMachine.add('wait_00', 
                                   Wait_State(1),
                                   transitions={'Complete': 'unfold'}) 

            smach.StateMachine.add('unfold', 
                                   unfold_sm,
                                   transitions={'Success': 'wait_1',
                                                'Fail': 'Mission_Fail'}) 

            smach.StateMachine.add('wait_1', 
                                   Wait_State(2),
                                   transitions={'Complete': 'poses_1'}) 
            
            smach.StateMachine.add('poses_1', 
                                   poses_sm,
                                   transitions={'Success': 'wait_2',
                                                'Fail': 'fold'}) 
            
            smach.StateMachine.add('wait_2', 
                                   Wait_State(2),
                                   transitions={'Complete': 'fold'}) 

            smach.StateMachine.add('fold', 
                                   fold_sm,
                                   transitions={'Success': 'Mission_Success',
                                                'Fail': 'Mission_Fail'}) 

    def run(self):
        outcome = self.sm.execute()


if __name__ == "__main__":
    rospy.init_node("mission_sm")
    sm = Mission_SM()
    print("Begin Run SM")
    sm.run()
