
unfold:
  step_0:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  
  step_1:
    - 3000.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0 
    - 0.0
    - 0.0
    - 0.0

  step_2:
    - 0.0
    - 20000.0
    - 0.0
    - 0.0
    - 0.0 
    - 0.0
    - 0.0
    - 0.0

  step_3:
    - 0.0
    - 0.0
    - -3000.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  step_4:
    - 0.0
    - 0.0
    - 0.0
    - 20000.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  step_5:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 3000.0
    - 0.0
    - 0.0
    - 0.0

  step_6:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - -5050.0
    - 0.0
    - 0.0

  step_9:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 2600.0
    - 0.0
    - 0.0


  step_7:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 90000.0
    - 0.0

  step_8:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1800000.0

  step_10:
    - 2100.0
    - 0.0
    - -8900.0
    - 0.0
    - 10000.0
    - 0.0
    - 0.0
    - 0.0

  step_11:
    - 2100.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  step_12:
    - 0.0
    - 0.0
    - -8900.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  step_13:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 10000.0
    - 0.0
    - 0.0
    - 0.0

catch:
  step_0:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 0.0
    - 0.0


