
launcher:
  step_0:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  step_1:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 17750.0
    - 0.0

  step_2:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  step_3:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 11000.0
    - 0.0
    - 0.0

  step_4:
    - 500.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

unfold:
  step_0:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  step_1:
    - -0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - -11000.0
    - 17750.0
    - 0.0

  step_2:
    - 0.0
    - 0.0
    - 1270.0
    - 0.0
    - -1460.0
    - -11000.0
    - 17750.0
    - 0.0

  step_3:
    - 0.0
    - 0.0
    - 1270.0
    - 0.0
    - -1460.0
    - 0.0
    - 17750.0
    - 0.0

  step_4:
    - -2880.0
    - 0.0
    - -2430.0
    - 0.0
    - 800.0
    - 0.0
    - 17750.0
    - 0.0

  step_5:
    - -2880.0
    - 0.0
    - -2430.0
    - 0.0
    - 4880.0
    - 0.0
    - 17750.0
    - 0.0

  step_6:
    - -5300.0
    - 0.0
    - -3850.0
    - 0.0
    - 975.0
    - 0.0
    - 17750.0
    - 0.0

  step_7:
    - -5300.0
    - 0.0
    - -2240.0
    - 0.0
    - 975.0
    - 0.0
    - 17750.0
    - 0.0

  step_8:
    - -5300.0
    - 0.0
    - -2240.0
    - 0.0
    - -1900.0
    - 0.0
    - 17750.0
    - 0.0

  step_9:
    - -5300.0
    - 0.0
    - 550.0
    - 0.0
    - -2000.0
    - 0.0
    - 17750.0
    - 0.0

  step_10:
    - -5300.0
    - 0.0
    - 550.0
    - -1200.0
    - -2000.0
    - 0.0
    - 17750.0
    - 0.0

  step_11:
    - -5300.0
    - 1540.0
    - 550.0
    - -1200.0
    - -2000.0
    - 0.0
    - 17750.0
    - 0.0

  step_12:
    - -5300.0
    - 1540.0
    - 4000.0
    - -1200.0
    - -2000.0
    - 0.0
    - 17750.0
    - 0.0

  step_13:
    - -5300.0
    - 0.0
    - 4000.0
    - 0.0
    - -2000.0
    - 0.0
    - 17750.0
    - 0.0

  step_14:
    - -5300.0
    - 0.0
    - 8440.0
    - 0.0
    - -195.0
    - 0.0
    - 17750.0
    - 0.0

  step_15:
    - -5300.0
    - 0.0
    - 8440.0
    - 0.0
    - 10835.0
    - 0.0
    - 17750.0
    - 0.0

  step_16:
    - -3540.0
    - 0.0
    - 8920.0
    - 0.0
    - 10835.0
    - 0.0
    - 17750.0
    - 0.0

pose:
  step_0:
    - -3540.0
    - 0.0
    - 8920.0
    - 0.0
    - 10835.0
    - 0.0
    - 17750.0
    - 0.0
  
 
catch:
  step_0:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 0.0
    - 0.0

  step_1:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 0.0
    - 0.0

  step_2:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 0.0
    - 0.0

ejector:
  step_0:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  step_1:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 17750.0
    - 0.0

second_ejector:
  step_0:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 17750.0
    - 0.0

  step_1:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 17750.0
    - 3600.0

third_ejector:
  step_0:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 17750.0
    - 3600.0

  step_1:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 17750.0
    - 7200.0

fourth_ejector:
  step_0:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 17750.0
    - 7200.0

  step_1:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 17750.0
    - 10800.0

grip: 
  step_0:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
     
  step_1:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - -11000.0
    - 0.0
    - 0.0

  step_2:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 11000.0
    - 0.0
    - 0.0