
launcher:
  step_0:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  step_1:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 17750.0
    - 0.0

unfold:
  step_0:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  step_1:
    - -0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - -11000.0
    - 0.0
    - 0.0

  step_2:
    - 0.0
    - 0.0
    - 1270.0
    - 0.0
    - -1460.0
    - -11000.0
    - 17750.0
    - 0.0

  step_3:
    - 0.0
    - 0.0
    - 1270.0
    - 0.0
    - -1460.0
    - 0.0
    - 17750.0
    - 0.0

  step_4:
    - -2880.0
    - 0.0
    - -2430.0
    - 0.0
    - 550.0
    - 0.0
    - 17750.0
    - 0.0

  step_5:
    - -2880.0
    - 0.0
    - -2430.0
    - 0.0
    - 4880.0
    - 0.0
    - 17750.0
    - 0.0

  step_6:
    - -5250.0
    - 0.0
    - -3850.0
    - 0.0
    - 975.0
    - 0.0
    - 17750.0
    - 0.0

  step_7:
    - -5054.0
    - 0.0
    - 2580.0
    - 0.0
    - 0.0
    - -1650.0
    - 0.0
    - 0.0


  step_99:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 12000.0
    - 0.0
    - 0.0
  
  
  
 
catch:
  step_0:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 0.0
    - 0.0

just_ball:
  step_0:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 17750.0
    - 3600.0
