
unfold:
  step_0:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  
  step_1:
    - -800.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0 
    - 0.0
    - 0.0
    - 0.0

  step_2:
    - 0.0
    - 800.0
    - 0.0
    - 0.0
    - 0.0 
    - 0.0
    - 0.0
    - 0.0

  step_3:
    - 0.0
    - 0.0
    - 800.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  step_4:
    - 0.0
    - 0.0
    - 0.0
    - 800.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0

  step_5:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 800.0
    - 0.0
    - 0.0
    - 0.0

  step_6:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 6000.0
    - 0.0
    - 0.0

  step_7:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0

  step_8:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0

catch:
  step_0:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 0.0
    - 0.0


